# Generated by Django 5.0.3 on 2024-05-15 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='게시글 아이디')),
                ('title', models.TextField(verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('upd_date', models.DateTimeField(null=True, verbose_name='수정일')),
                ('count', models.CharField(max_length=255, verbose_name='조회수')),
                ('type_team', models.CharField(max_length=255, verbose_name='팀 분류')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='프로필 아이디')),
            ],
        ),
    ]
