# Generated by Django 5.0.3 on 2024-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_article_user_id_article_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='유저 이름'),
        ),
    ]
