# Generated by Django 5.0.3 on 2024-05-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_article_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='count',
            field=models.CharField(default=0, max_length=255, verbose_name='조회수'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('upd_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('nickname', models.CharField(max_length=100, verbose_name='유저 이름')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boards.article', verbose_name='게시글')),
            ],
        ),
    ]
